apiVersion: v1
kind: Service
metadata:
  name: node-test-services
  labels:
    app: node-server
spec:
  type: NodePort
  selector:
    app: node-server
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 31000
