groups:
  - name: Production
    jobs: 
     - job-run-master
  - name: Develop
    jobs: 
     - job-run-develop    
  - name: Feature
    jobs: 
     - job-run-feature  

resources:
- name: repo-master
  type: git
  source: 
    uri: https://github.com/ibohalsinghkoijam/restapi-flow-yarn-concourse.git
    branch: master

- name: repo-develop
  type: git
  source: 
    uri: https://github.com/ibohalsinghkoijam/restapi-flow-yarn-concourse.git
    branch: develop

- name: repo-feature
  type: git
  source: 
    uri: https://github.com/ibohalsinghkoijam/restapi-flow-yarn-concourse.git
    branch: feature/*

jobs:
# - name: job-run-master
#   public: true
#   plan:
#    - get: repo-basic
#      resource: repo-master
#      trigger: true
#    - task: unit-test-master
#      file: repo-basic/ci/unit.yml

- name: job-run-master
  public: true
  plan:
    - get: repo-basic
      resource: repo-master
      trigger: true
    - task: unit-test-master
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: node, tag: "8" }
        inputs:
          - name: repo-basic
        run:
          path: /bin/sh
          args:
            - -c
            - |
              echo "Node Version: $(node --version)"
              echo "NPM Version: $(npm --version)"
              cd repo-basic
              yarn install
              yarn test

- name: job-run-develop
  public: true
  plan:
   - get: repo-basic
     resource: repo-develop
     trigger: true
   - task: unit-test-develop
     file: repo-basic/ci/unit.yml

- name: job-run-feature
  public: true
  plan:
   - get: repo-basic
     resource: repo-feature
     trigger: true
   - task: unit-test-develop
     file: repo-basic/ci/unit.yml