groups:
  - name: Production
    jobs: 
     - job-run-master
     - job-push-master
    #  - job-deploy-master
  - name: Develop
    jobs: 
     - job-run-develop    
  - name: Feature
    jobs: 
     - job-run-feature  

resources:
- name: repo-master
  type: git
  source: &git-repo
      uri: ((git_url))
      # username: ((username))
      # password: ((password))
      branch: master
  # source: 
  #   uri: https://github.com/ibohalsinghkoijam/restapi-flow-yarn-concourse.git
  #   branch: master

- name: my-dockerhub
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/node-server

# - name: aws-repo-master
#     type: docker-image
#     source: &ecr-repo
#       aws_access_key_id: ((aws_access_key_id))
#       aws_secret_access_key: ((aws_secret_access_key))
#       repository: ((aws_prod_repository))

- name: repo-develop
  type: git
  source: 
    uri: https://github.com/ibohalsinghkoijam/restapi-flow-yarn-concourse.git
    branch: develop

- name: repo-feature
  type: git
  source: 
    uri: https://github.com/ibohalsinghkoijam/restapi-flow-yarn-concourse.git
    branch: feature/*

jobs:
# - name: job-run-master
#   public: true
#   plan:
#    - get: repo-basic
#      resource: repo-master
#      trigger: true
#    - task: unit-test-master
#      file: repo-basic/ci/unit.yml

- name: job-run-master
  public: true
  plan:
    - get: repo-basic
      resource: repo-master
      trigger: true
    - task: unit-test-master
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: node, tag: "8" }
        inputs:
          - name: repo-basic
        run:
          path: /bin/sh
          args:
            - -c
            - |
              echo "Node Version: $(node --version)"
              echo "NPM Version: $(npm --version)"
              cd repo-basic
              yarn install
              yarn test
# - name: job-push-master
#     public: true
#     plan:
#       - get: repo-basic
#         resource: repo-master
#         trigger: true
#         passed: [job-build-master]
#       - put: aws-repo-master
#         params:
#           build: repo-basic
#           build_args:
#             NG_BUILD_TARGET: prod
#           dockerfile: repo-basic/Dockerfile
- name: job-push-master
  public: true
  plan:
    - get: repo-basic
      resource: repo-master
      version: "every"
      trigger: true
      passed: [job-run-master]
    - put: my-dockerhub
      params:
        build: repo-basic
        dockerfile: repo-basic/Dockerfile

- name: job-run-develop
  public: true
  plan:
   - get: repo-basic
     resource: repo-develop
     trigger: true
   - task: unit-test-develop
     file: repo-basic/ci/unit.yml

- name: job-run-feature
  public: true
  plan:
   - get: repo-basic
     resource: repo-feature
     trigger: true
   - task: unit-test-develop
     file: repo-basic/ci/unit.yml